version: '3.8'
  
services:
    web:
      build: .
      command: python /code3/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code3
      ports:
        - 8000:8000
      depends_on:
        - db
    db:
      image: postgres:13
      volumes:
        - postgres_data3:/var/lib/postgresql/data/
      environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data3: